server:
  port: 9000
  servlet:
    context-path: /user

# JPA
spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # import application-oauth.yml
  profiles:
    include: local

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug
    org.hibernate.sql: debug



