version: '3'
services:
  spring:
    container_name: 'spring-filesave-container'
    build:
      context: .    # Build Context Directory
      dockerfile: ./Dockerfile      # Dockerfile
    ports:
      - "9001:9001"
    volumes:    # Connect Local Volume
      - /home/ubuntu/file_volume:/Home
    networks:
      - dub-network
networks:
  dub-network:
     external: true
