export enum CheckMessageStatus {
    ISVALID = "ISVALID",
    NICKNAME_DUPLICATION = "NICKNAME_DUPLICATION",
    NICKNAME_LIMIT_SIX = "NICKNAME_LIMIT_SIX",
    INTRODUCE_LIMIT_FIFTEEN = "INTRODUCE_LIMIT_FIFTEEN"
}

export enum CommonAlertType {
    DUBBING_OUT = "DUBBING_OUT",
    COMMENT_DELETE = "COMMENT_DELETE",
    CONTENTS_DELETE = "CONTENTS_DELETE",
}